services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker-test

  redis:
    image: redis
    container_name: cache-test
    ports:
      - "6379:6379"